"""Interactive first-run setup: ``python main.py init [target_dir]``."""

import asyncio
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Callable, TypeVar
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import yaml
from telegram import Bot
from telegram.error import TelegramError
from telethon import TelegramClient
from telethon.errors import ApiIdInvalidError

from src.config_loader import _PROVIDER_DEFAULT_MODELS, SUPPORTED_LANGUAGES

T = TypeVar("T")

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_HEADER = (
    "# Generated by `telebrief init`. All options: "
    "https://github.com/belaytzev/Telebrief/blob/main/config.yaml.example\n"
)
PROVIDER_KEY_ENV = {"openai": "OPENAI_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    return input(f"{prompt}{suffix}: ").strip() or default


def ask_until(prompt: str, parse: Callable[[str], T], default: str = "") -> T:
    while True:
        try:
            return parse(ask(prompt, default))
        except ValueError as e:
            print(f"  ✗ {e}")


def ask_choice(prompt: str, options: list[str], default: str) -> str:
    print(prompt)
    for i, opt in enumerate(options, 1):
        print(f"  {i}. {opt}")

    def parse(text: str) -> str:
        if text in options:
            return text
        if text.isdigit() and 1 <= int(text) <= len(options):
            return options[int(text) - 1]
        raise ValueError(f"Enter a number 1-{len(options)}")

    return ask_until("Choice", parse, default)


def confirm(prompt: str) -> bool:
    return ask(f"{prompt} [y/N]").lower() in ("y", "yes")


def parse_selection(text: str, count: int) -> list[int]:
    """Parse "1,4,7-9" into sorted zero-based indices within ``count``."""
    picked: set[int] = set()
    for part in text.replace(" ", "").split(","):
        if not part:
            continue
        lo, _, hi = part.partition("-")
        if not lo.isdigit() or (hi and not hi.isdigit()):
            raise ValueError(f"Can't parse '{part}', use e.g. 1,4,7-9")
        start, end = int(lo), int(hi or lo)
        if not 1 <= start <= end <= count:
            raise ValueError(f"'{part}' is out of range 1-{count}")
        picked.update(range(start - 1, end))
    if not picked:
        raise ValueError("Pick at least one channel")
    return sorted(picked)


def parse_api_id(text: str) -> int:
    if not text.isdigit():
        raise ValueError("api_id is a number")
    return int(text)


def parse_non_empty(text: str) -> str:
    if not text:
        raise ValueError("Value is required")
    return text


def parse_time(text: str) -> str:
    try:
        datetime.strptime(text, "%H:%M")
    except ValueError:
        raise ValueError("Use HH:MM, e.g. 08:00") from None
    return text


def parse_timezone(text: str) -> str:
    try:
        ZoneInfo(text)
    except (ZoneInfoNotFoundError, ValueError):
        raise ValueError("Unknown timezone, use e.g. UTC or Europe/Berlin") from None
    return text


def parse_phone(text: str) -> str:
    phone = text.replace(" ", "").replace("-", "")
    if ":" in phone:
        raise ValueError("That looks like a bot token — enter your own phone number here")
    if not phone.lstrip("+").isdigit() or len(phone) < 7:
        raise ValueError("Use international format, e.g. +1234567890")
    return phone


def ask_phone() -> str:
    return ask_until("Your phone number (+1234567890)", parse_phone)


def ask_credentials() -> tuple[int, str]:
    return ask_until("api_id", parse_api_id), ask_until("api_hash", parse_non_empty)


async def sign_in_user(client: TelegramClient) -> None:
    while True:
        try:
            # Telethon's default prompt also accepts a bot token and silently logs in as the bot.
            await client.start(phone=ask_phone)
            return
        # start() gives up for good once a code expires (ValueError) or is wrong three times
        except (ValueError, RuntimeError):
            print("  ✗ The login code expired or was wrong, requesting a new one")


async def login(session_path: Path) -> tuple[TelegramClient, dict[str, str], int]:
    print("\n1) Telegram API credentials — create an app at https://my.telegram.org/apps")
    print("   If it shows ERROR, see the troubleshooting notes in README.md\n")
    api_id, api_hash = ask_credentials()
    while True:
        client = TelegramClient(str(session_path), api_id, api_hash)
        try:
            await sign_in_user(client)
        except ApiIdInvalidError:
            await client.disconnect()
            print("  ✗ Telegram rejected this api_id/api_hash pair, try again")
            api_id, api_hash = ask_credentials()
            continue
        me = await client.get_me()
        if not me.bot:
            break
        await client.log_out()
        print("  ✗ The saved session belongs to a bot. Log in with your personal account")
    print(f"  ✓ Logged in as {me.first_name} (id {me.id})")
    env = {"TELEGRAM_API_ID": str(api_id), "TELEGRAM_API_HASH": api_hash}
    return client, env, me.id


async def ask_bot_token() -> tuple[str, str]:
    print("\n2) Bot token — send /newbot to @BotFather\n")
    while True:
        token = ask_until("Bot token", parse_non_empty)
        try:
            async with Bot(token) as bot:
                username = (await bot.get_me()).username or ""
        except TelegramError as e:
            print(f"  ✗ Token rejected: {e}")
            continue
        print(f"  ✓ Bot @{username}")
        return token, username


def ask_ai() -> tuple[dict[str, str], dict[str, object]]:
    print("\n3) AI provider")
    provider = ask_choice("Provider:", list(_PROVIDER_DEFAULT_MODELS), "openai")
    settings: dict[str, object] = {"ai_provider": provider}
    settings["ai_model"] = ask("Model", _PROVIDER_DEFAULT_MODELS[provider])
    env: dict[str, str] = {}
    if provider in PROVIDER_KEY_ENV:
        env[PROVIDER_KEY_ENV[provider]] = ask_until("API key", parse_non_empty)
    else:
        print("  Note: on Linux host.docker.internal needs extra_hosts in docker-compose.yml")
        settings["ollama_base_url"] = ask("Ollama URL", "http://host.docker.internal:11434")
    return env, settings


def ask_output() -> dict[str, str]:
    print("\n4) Output")
    return {
        "output_language": ask_choice("Digest language:", list(SUPPORTED_LANGUAGES), "Russian"),
        "schedule_time": ask_until("Daily digest time (HH:MM)", parse_time, "08:00"),
        "timezone": ask_until("Timezone", parse_timezone, "UTC"),
    }


async def pick_channels(client: TelegramClient) -> list[dict]:
    print("\n5) Channels to digest")
    dialogs = [d async for d in client.iter_dialogs() if d.is_channel or d.is_group]
    if not dialogs:
        print("  No channels or groups found — add them to config.yaml later")
        return []
    for i, d in enumerate(dialogs, 1):
        print(f"  {i:>3}. {d.name}")
    picked = ask_until("Numbers (e.g. 1,4,7-9)", lambda text: parse_selection(text, len(dialogs)))
    return channel_entries([(dialogs[i].id, dialogs[i].name) for i in picked])


def channel_entries(pairs: list[tuple[int, str]]) -> list[dict]:
    """Build config entries; config_loader rejects duplicate names, so suffix them with the id."""
    names = [name for _, name in pairs]
    return [
        {"id": cid, "name": name if names.count(name) == 1 else f"{name} ({cid})"}
        for cid, name in pairs
    ]


def render_files(env: dict[str, str], channels: list[dict], settings: dict) -> dict[str, str]:
    config = {"channels": channels, "settings": settings}
    return {
        ".env": "".join(f"{k}={v}\n" for k, v in env.items()),
        "config.yaml": CONFIG_HEADER + yaml.safe_dump(config, allow_unicode=True, sort_keys=False),
        "docker-compose.yml": (REPO_ROOT / "docker-compose.yml").read_text(),
    }


def write_files(target: Path, files: dict[str, str]) -> None:
    for name, content in files.items():
        path = target / name
        if path.exists() and not confirm(f"{path} exists. Overwrite?"):
            print(f"  – kept existing {name}")
            continue
        path.write_text(content)
        if name == ".env":
            path.chmod(0o600)
        print(f"  ✓ wrote {name}")


async def run_wizard(target: Path) -> None:
    sessions = target / "sessions"
    sessions.mkdir(parents=True, exist_ok=True)
    client, env, user_id = await login(sessions / "user")
    try:
        token, bot_username = await ask_bot_token()
        env["TELEGRAM_BOT_TOKEN"] = token
        ai_env, settings = ask_ai()
        env.update(ai_env)
        settings.update(ask_output())
        channels = await pick_channels(client)
    finally:
        await client.disconnect()

    settings["target_user_id"] = user_id
    print(f"\n6) Writing files to {target}")
    write_files(target, render_files(env, channels, settings))
    print(
        f"\nDone. Next:\n"
        f"  1. Open https://t.me/{bot_username} and press Start\n"
        f"  2. docker compose up -d\n"
        f"  3. Send /digest to the bot\n"
    )


def main(target_dir: str) -> int:
    if not sys.stdin.isatty():
        print("Setup is interactive: run docker with -it")
        return 1
    target = Path(target_dir).resolve()
    target.mkdir(parents=True, exist_ok=True)
    if not os.access(target, os.W_OK):
        print(f'{target} is not writable: add --user "$(id -u):$(id -g)" to docker run')
        return 1
    print(f"Telebrief setup — files will be written to {target}")
    try:
        asyncio.run(run_wizard(target))
    except (KeyboardInterrupt, EOFError):
        print("\nSetup cancelled")
        return 1
    return 0
